// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXhH6rQYw4k1ta3b6UHE1l054bfeCm7xk',
    appId: '1:841642444471:web:243239280afdca465aef32',
    messagingSenderId: '841642444471',
    projectId: 'simple-chat-app-cd66a',
    authDomain: 'simple-chat-app-cd66a.firebaseapp.com',
    storageBucket: 'simple-chat-app-cd66a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP1ZZH0AgVePS2eWfI_ZggfOtRmmsmHeY',
    appId: '1:841642444471:android:3061d6dcaeb938e35aef32',
    messagingSenderId: '841642444471',
    projectId: 'simple-chat-app-cd66a',
    storageBucket: 'simple-chat-app-cd66a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAst03dq5ic6m8F_U0Tnb5srxUNLmjKFF4',
    appId: '1:841642444471:ios:e990e40ffccf433d5aef32',
    messagingSenderId: '841642444471',
    projectId: 'simple-chat-app-cd66a',
    storageBucket: 'simple-chat-app-cd66a.appspot.com',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAst03dq5ic6m8F_U0Tnb5srxUNLmjKFF4',
    appId: '1:841642444471:ios:e990e40ffccf433d5aef32',
    messagingSenderId: '841642444471',
    projectId: 'simple-chat-app-cd66a',
    storageBucket: 'simple-chat-app-cd66a.appspot.com',
    iosBundleId: 'com.example.simpleChatApp',
  );
}
